README.md
Add a missing comma in the sample job JSON
=> Fix sample job json

src/main/scala/com/airbnb/scheduler/mesos/MesosJobFramework.scala
Mesos allows frameworks to respond to offers with a list of tasks to run.
Currently, Chronos launches at most task per offer. I think it would be helpful to respond with many tasks from the queue per offer to reduce the delay between getting added to the queue and being launched on Mesos.
This patch accomplishes this in a simple way by repeatedly popping tasks from the queue as long as there are resources remaining to satisfy them, and then launches them all together.
=> Allow launching multiple tasks per resource offer

pom.xml
Bump up the version number since there have been a number of recent changes.
=> Bump up version number

src/test/scala/com/airbnb/scheduler/jobs/JobSchedulerIntegrationTest.scala
ScheduledThreadPoolExecutor(1) as listeningDecorator does not work on all build environments. For this unit test, we have updated it to use the mock layer.
=> Fix build issue on team city env

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala, src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
This depends on #351.
cc @elingg
=> Job retry policy

README.md
The Readme still had the old package structure for the main class.
=> Fixing the package to execute the main scheduler.

src/main/scala/org/apache/mesos/chronos/scheduler/api/JobManagementResource.scala, src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala, src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskUtils.scala, src/test/scala/org/apache/mesos/chronos/scheduler/jobs/TaskUtilsSpec.scala
=> Fix null args, variable shadowing.

src/main/scala/org/apache/mesos/chronos/scheduler/graph/JobGraph.scala, src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
=> Remove deprecated synchronizedmap

src/main/scala/org/apache/mesos/chronos/scheduler/api/RedirectFilter.scala
Add leader's url to proxy log to to check whether proxy to the right
one.
=> Add leader's url to proxy log

src/main/scala/org/apache/mesos/chronos/scheduler/state/MesosStatePersistenceStore.scala
Func removeTask uses task name without prefix "T_".
=> Fix: cleaning invalid task with a wrong task name

pom.xml
Bump up the version number for release
=> Update version number

README.md
=> Docs: remove note about jobs without schedules.

src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala
=> Enable checkpointing by default.

README.md
Related to my pain in #389, it would have helped if the README was clearer. Here's a small change that should make things more obvious to fellow newbies!
=> Update environmentVariables in sample job to make the structure clear.

pom.xml, src/main/scala/org/apache/mesos/chronos/scheduler/config/MainModule.scala, src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala
Tests pass, and tested setting the commandline option.
=> Add webui_url to FrameworkInfo

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala
When an offer is refused, we wait 5 secs before receiving that offer
again (consistent with Marathon). This will have an effect on triggered
jobs, in that they will be a short delay in triggering them. However,
it will ensure that Chronos doesn’t receive and decline offers too
frequently and that Chronos doesn’t receive more than it’s fair share
of offers.
=> Set the offer frequency to 5 secs

README.md
Would like to improve the documentation around configuring Chronos logging.
=> Improving log documentation

pom.xml
=> Update mesos-utils to latest version (0.22.0-1).

Dockerfile
=> [CHRONOS-412] - docker build hangs waiting for gpg key

pom.xml
=> Updated Chaos to latest version 0.6.5

src/main/scala/org/apache/mesos/chronos/scheduler/api/DependentJobResource.scala
This fixes an issue where a job that depends on two or more parent jobs
is not executed if it was updated while some of the parent jobs
have finished while others are still running.
=> Fix dependent job not run if it got updated

src/main/resources/assets/app/index.html, src/main/resources/assets/app/scripts/bargraph.js, src/main/resources/assets/app/scripts/collections/job_graph.js, src/main/resources/assets/app/scripts/collections/jobs.js, src/main/resources/assets/app/scripts/models/base_job.js, src/main/resources/assets/app/scripts/models/dependent_job.js, src/main/resources/assets/app/scripts/models/scheduled_job.js, src/main/resources/assets/app/scripts/styles/core.less, src/main/resources/assets/app/scripts/styles/select2.less, src/main/resources/assets/app/scripts/styles/variables.less, src/main/resources/assets/app/scripts/views/graph_viz_view.js, src/main/resources/assets/app/scripts/views/job_detail_view.js
This enables the Chronos UI to be run through proxied calls by making requests to the API and assets like images relative.
F.ex. http://dcos/chronos/#jobs/job1 is now working.
=> Making paths relativ to enable proxied requests

docs/docs/api.md, src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Containers.scala, src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala, src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala, src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala, src/test/scala/org/apache/mesos/chronos/scheduler/api/SerDeTest.scala
=> Add support for docker_force_pull (#345)

docs/docs/api.md
Bad rendering on https://mesos.github.io/chronos/docs/api.html#adding-a-scheduled-job
=> Fix rendering typo in api.md

docs/docs/api.md
=> Document the job name requirements

README.md
Warn users that the GUI currently drops fields on update.
=> Add a warning to the README

docs/resources.md
=> Add Go client to docs

.travis.yml
Did a quick test to make sure Travis is actually working. All is well.
cc @ssk2
=> Cache maven artifacts with Travis.

src/main/resources/assets/app/scripts/styles/core.less
This fixes https://github.com/mesos/chronos/issues/597
cc @mwasn
=> Prevent jobs list from collapsing in small screens

README.md
http://uxresearch.mesosphere.com
To help recruit more users for Chronos testing
=> Add link to UX Research capture form

src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala, src/main/scala/org/apache/mesos/chronos/scheduler/config/ZookeeperModule.scala
=> Allow to authorize with ZooKeepe by zooKeeperAuth.

src/main/scala/org/apache/mesos/chronos/scheduler/api/Iso8601JobResource.scala
=> Don't allow schedules more than 1 year in the past.

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala, src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala
This pull request fixes https://github.com/mesos/chronos/issues/777.
=> Job command is now an optional parameter

src/main/resources/ui/models/JobForm.js
Attempts to resolve issue #785
=> Update UI to allow periods in container image name

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Fetch.scala, src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala, src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala, src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala, src/test/scala/org/apache/mesos/chronos/scheduler/api/SerDeTest.scala
=> Support fetcher output_file parameter.

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala, src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtils.scala, src/test/scala/org/apache/mesos/chronos/scheduler/jobs/Iso8601ExpressionParserSpec.scala, src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtilsSpec.scala
=> Fix for regression of finite recurrence jobs.

src/main/scala/org/apache/mesos/chronos/scheduler/api/Iso8601JobResource.scala
=> Allow start dates after 1970.

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/SchedulerDriverBuilder.scala
=> Set auth params as bytes, instead of string.

src/main/resources/ui/models/JobForm.js
The regex should also accept - and _.
This fixes the issue noted in #785.
=> Update image regex in UI.
