mesos/chronos

src/main/scala/com/airbnb/scheduler/jobs/JobScheduler.scala
src/test/scala/com/airbnb/scheduler/jobs/JobSchedulerIntegrationTest.scala

This fixes a failing test, caused by an invalid start date for the schedule stream.
CC @airbnb/di @elingg

Chronos build fix

---

.gitignore
README.md
pom.xml
src/main/scala/com/airbnb/scheduler/api/JobManagementResource.scala
src/main/scala/com/airbnb/scheduler/jobs/JobScheduler.scala
src/main/scala/com/airbnb/scheduler/jobs/JobUtils.scala
src/main/scala/com/airbnb/scheduler/jobs/TaskManager.scala
src/main/scala/com/airbnb/scheduler/jobs/TaskUtils.scala
src/main/scala/com/airbnb/scheduler/mesos/MesosJobFramework.scala
src/test/scala/com/airbnb/scheduler/jobs/JobUtilsSpec.scala
src/test/scala/com/airbnb/scheduler/jobs/TaskUtilsSpec.scala

This commit adds support for passing custom command arguments when manually running a Chronos job using `PUT /scheduler/<jobName>` endpoint
see https://github.com/airbnb/chronos/issues/335

Support for custom command arguments when manually running a Chronos job

---

README.md

Updated docs as per [comment] (https://github.com/mesos/chronos/pull/337#issuecomment-70179794)

Updated docs. Replaced example argument to be -debug

---

src/main/scala/com/airbnb/scheduler/config/SchedulerConfiguration.scala

This will match Marathon’s default.

Increase default failover timeout to 1 week

---

bin/chronos-sync.rb

Forgot to add this when I added support to the PUT command.

Add basic auth support for http DELETE command

---

README.md
bin/chronos-marathon
bin/chronos.debian.init
bin/run
bin/start-chronos.bash
bin/ubuntu.bash

The code had more instances of using the old package structure com.airbnb instead of the current org.apache.mesos package.

There were more instances of the old package structure

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala

Chronos will be unable to decline offers from mesos and will hold all
the mesos resources if exception happends on loading tasks or jobs.
It may be caused by bad network to ZKServer or some other reasons,
exit with code 1.

Fix: Add try-catch to loading tasks and jobs

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala

Task will be loaded on restarting. It's meaningless.

Remove invalid tasks on scheduling

---

bin/chronos-sync.rb

Expose more variables to yaml file, to allow an user to have more control over job management.

expose more job variables via yaml files

---

bin/chronos-sync.rb

If a job is missing fields which aren't mandatory, they should just be
ignored when comparing jobs.
cc @elingg

[chronos-sync] Undefined fields should be ignored.

---

bin/chronos-sync.rb

We have an automated script that generates chronos jobs and syncs them with Chronos.  We'd like to be able to delete missing jobs without the prompt.

Support disabling prompt for deleting missing jobs

---

src/main/scala/org/apache/mesos/chronos/notification/SlackClient.scala
src/main/scala/org/apache/mesos/chronos/scheduler/config/MainModule.scala
src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala

Slack has changed their web hook format, this update makes the Slack integration work again.

Updating Slack integration to comply with new Slack webhook format

---

src/main/scala/org/apache/mesos/chronos/notification/SlackClient.scala

Whoops - should have added this in the last PR.  Having the subject in the slack notification helps distinguish what environment the alert is coming from.

Adding subject to Slack notification

---

bin/chronos-sync.rb

The chronos-sync.rb script currently has logic in it to skip jobs ahead if they have a schedule in the past.  However, this logic is broken for irregular intervals (P1M, for example).  As you can see below, it incorrectly sets the new date to 2015-04-02 instead of 2015-04-01. 
Schedule for 'build_gas_stubs' begins in the past!  Resetting to from R/2014-09-01T11:05:00-04:00/P1M to R/2015-04-02T11:05:00.000-04:00/P1M
Chronos itself already has logic to do this (in JobUtils.makeScheduleStream), so I'm not sure if it's still necessary to do so in the sync script.

Remove chronos-sync skip logic

---

README.md
src/main/resources/assets/app/scripts/models/base_job.js
src/main/resources/assets/app/scripts/templates/job_detail_view.hbs
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Jobs.scala
src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala
src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala
src/test/scala/org/apache/mesos/chronos/scheduler/api/SerDeTest.scala

This commit adds backend support for job description and owner name fields, plus support for viewing and editing these fields via the Chronos web UI.
Here's a screenshot showing the UI changes:

Adding description and owner name fields to jobs

---

README.md
src/main/scala/org/apache/mesos/chronos/scheduler/config/MainModule.scala
src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosDriverFactory.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

To use the credentials in chronos:
* Run mesos-master with the credentials flag and the path to file with authorized users + their secrets. 
`--credentials=/path/to/credential/file`
> Each line in the file should be a principal space separated with their password. 
```bash
$ cat /path/to/credential/file
principal secret
principal2 secret2
```
* Run chronos with the `--mesos_authentication_principal` flag and optionally with the   
`--mesos_authentication_secret_file` flag that contains the secret.
> The secret file cannot have a trailing newline. To not add a newline simply run:
```bash
$ echo -n "secret" > /path/to/secret/file
```

Chronos Credential Support

---

src/main/scala/org/apache/mesos/chronos/scheduler/Main.scala

Chronos may be hanging when exception happens during initing. Althought
it's hard to reappear, it should be handled.

Add try-catch block for initialization

---

README.md
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/Jobs.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/Constraint.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/EqualsConstraint.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala
src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala
src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala
src/test/scala/org/apache/mesos/chronos/scheduler/api/SerDeTest.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/EqualsConstraintSpec.scala

This PR adds support for `constraints` as described in #256.
The format to define constraints of a job is the same as in Marathon.
Note that currently only the `CLUSTER` constraint has been implemented.

Add constraints

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

Add better logging for when a job cannot be scheduled due to insufficient resources.
Resolution for https://github.com/mesos/chronos/issues/394
@elingg 
@michaeljin

Better logging for insufficient resources

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManagerSpec.scala

Fix error on chronos startup. 
This fixes a bug I encountered recently. I had deleted some tasks from the chronos UI and when I bounced chronos, it wouldn't come up. The error in the logs pointed to the culprit here:
```
java.util.NoSuchElementException: None.get
```
It looks like code exists to handle the case when jobOption is empty, but we still unconditionally dereference the jobOption.

FIX: Handle None return in getTask

---

src/main/scala/org/apache/mesos/chronos/notification/JobNotificationObserver.scala
src/main/scala/org/apache/mesos/chronos/scheduler/api/JobManagementResource.scala
src/main/scala/org/apache/mesos/chronos/scheduler/api/JobStatWrapperSerializer.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobsObserver.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/ScheduleStream.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskStat.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/graph/Exporter.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/stats/JobStats.scala
src/main/scala/org/apache/mesos/chronos/scheduler/state/MesosStatePersistenceStore.scala
src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobSchedulerIntegrationTest.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobSchedulerSpec.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/ScheduleStreamSpec.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManagerSpec.scala

This PR contains #436 in it. It adds proper firing of JobQueued via the new interface and adds JobExpired callback. It also makes corresponding methods in JobStats private, to make sure that they are not called from anywhere but the Observer interface.
Out of boredom, I cleaned up a good number of warnings in several classes to make IntelliJ happy.

Cleanup of compiler warnings and complete JobStats refactoring

---

Dockerfile
bin/start-chronos.bash

As per Docker-Library best practices, it's best to  allow  overriding ENTRYPOINT, when needed by checking  for  "-"  arguments.
Examples:
`docker run -it chronos` is possible, and so is passing flags:
`docker run -it chronos --help` will work as expected / before.
`docker run -it chronos /bin/bash` and similar is now possible.
See https://github.com/docker-library/official-images/issues/692

DOCKER: better entrypoint

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

Chronos should accept offers for role '*' when running with a role other than '*'.

Accept offers with role '*' with --mesos_role

---

src/main/scala/org/apache/mesos/chronos/scheduler/config/ZookeeperModule.scala

Chronos may get a wrong leader path, which may cause a fatal error that:
once the non-leader instance gets an out-of-date leader path and the wrong
path happens to be itself, it will redirects a request to itself  and
then blocks other any requests in less than 1 second. In this circumstance,
scheduler is still running but no rest api responds, even it becomes leader.
So, setting connecting parameter 'canBeReadOnly' to false(default) to provide
Chronos from reading wrong leader info is necessary.

Forbid using canBeReadonly when connecting zookeeper

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

MesosDriver may crash during launching tasks, and it that case task is not
submitted to mesos but removed from persistence storage. Keep task util it
really executes on mesos.

Remove persistence task after mesos task running

---

docs/docs/api.md
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/LikeConstraint.scala
src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala
src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala
src/test/scala/org/apache/mesos/chronos/scheduler/api/SerDeTest.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/ConstraintSpecHelper.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/EqualsConstraintSpec.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/LikeConstraintSpec.scala

The PR adds a new constraint called LIKE which matches the value of an
attribute of a slave against a regular expression.

Add LIKE constraint

---

README.md

The chronos docs look strange on http because of a lack of js on one of the cdns. This fixes that.
Also https is good.

Made doc links use https

---

docs/docs/api.md

Fixes #490.
The "Manually Starting a Job" section on http://mesos.github.io/chronos/docs/api.html recommends using the 'arguments' parameter, but doesn't mention that 'shell' must be set to false for it to work. This should be clarified/fixed.

Clarify arguements param on manual job starts.

---

docs/docs/configuration.md

Hey, thanks for all the great work on Chronos.
I find some parts of the documentation impossible to use. Especially as Chronos is such a cornerstone of DCOS, more and more users like myself will be searching for how to configure chronos.
This adds a quick dump of command line flags to the Configuring page. I know a similar list was removed in 9edee8457847e380e5bc822f6d27854616299e25, but I think it is unacceptable to instruct users to install (or worse, build) your software in order to see the list of configuration options.
Thanks again.

Add list of command line arguments to documentation

---

pom.xml
src/main/scala/org/apache/mesos/chronos/scheduler/config/MainModule.scala
src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosDriverFactory.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosOfferReviver.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosOfferReviverActor.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosOfferReviverDelegate.scala
src/main/scala/org/apache/mesos/chronos/utils/Timestamp.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManagerSpec.scala
src/test/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFrameworkSpec.scala
src/test/scala/org/apache/mesos/chronos/scheduler/mesos/MesosOfferReviverActorSpec.scala
src/test/scala/org/apache/mesos/chronos/scheduler/mesos/MesosOfferReviverDelegateSpec.scala

@ConnorDoyle @elingg @brndnmtthws 
**NOTE**: I plan to add some tests tomorrow, but I would really appreciate if I could get any feedback in the meantime. This has already been done to Marathon, please see https://github.com/mesosphere/marathon/issues/1931.
Add the following command line flags:
`--revive_offers_for_new_jobs` if true, revive offers is called when a new job
is added to the `TaskManager`.
Also note, that Mesos only filters offers that are a strict sub set of a
rejected offer.
`--decline_offer_duration` allows configuring the duration for which unused
offers are declined.
`--min_revive_offers_interval` if `--revive_offers_for_new_jobs` is specified,
do not call reviveOffers more often than this interval. It defaults to 5
seconds.

Fixes #509 - Flag for reviveOffers and the duration for which to reject offers

---

docs/docs/api.md

Mostly minor style/formatting changes for improved readability. Added some wording and links for clarity. One important correction: the `shell` parameter of a job configuration was documented as a string, but it's actually a boolean.

Minor API documentation improvements and corrections

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala

Old tasks can take up a lot of space in the persistence store, and can cause chronos to take a long time to start up as it cleans them up. It seems nicer to remove these tasks from the persistence store when they complete.

remove task from persistence store on completion

---

src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/SchedulerDriverBuilder.scala

Due to a bug in Mesos < 0.24.0, Marathon users have observed JVM crashes
when the framework the host's hostname is nor resolvable
(https://issues.apache.org/jira/browse/MESOS-3145).
This change works around the problem by setting the hostname in the
Framework Information proto.

Set the hostname in the framework information proto

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtils.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtilsSpec.scala

Marathon [allows](https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/mesosphere/marathon/api/v2/AppsResource_create.md#id-string) periods in job names, but Chronos rejects jobs with periods in their names. Periods are useful as a delimiter, and there's no obvious reason why they aren't allowed in job names. I updated the regex to allow periods and added a test to check that the job name validation accepts a job name containing periods.
Tests [ran](https://travis-ci.org/carroux/chronos/builds/77242330#L3941) and [passed](https://travis-ci.org/carroux/chronos/builds/77242330#L3946).

Allow periods in job names

---

Dockerfile

Removed node package as it is a radio package in Debian/Ubuntu. Added symlink /usr/bin/node pointing at /usr/bin/nodejs.

Fix Dockerfile so node works with Ubuntu base image

---

docs/docs/api.md

Prior to this commit, there was a Markdown formatting problem with the
API docs. This resulted in a bunch of (what should have been) bullet
points appearing as normal text, and making the explanation of the ISO
8601 format harder to read than it needed to be.
This commit modifies some of the API documentation to correctly format
the bullet list for the "Adding a Scheduled Job" section.

fix a formatting issue with api docs

---

docs/docs/api.md

Fix the job listing lastSuccess and lastError type. It's actually a date not a timestamp.

Fix the job listing lastSuccess and error type

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtils.scala

correction #561

---

docs/docs/contributing.md
pom.xml

@aquamatthias 
Let's get this into teamcity build reports.

Add SCoverage for generating test coverage reports

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

I spent hours trying to debug a chronos job not working, but I was misled by this line because it said things like this:
```
WARN Insufficient resources remaining for task 'ct:1453417002396:0:paasta_canary sensu_canary git6c3833b5 config7708a392:', will append to queue. (Needed: [cpus: 0.1 mem: 256.0 disk: 256.0], Found: [cpus: 3.4499999990000014 mem: 22635.0 disk: 10000.0,cpus: 7.369999999999992 mem: 30363.0 disk: 10000.0,cpus: 2.5700000000000003 mem: 18051.0 disk: 10000.0,cpus: 7.349999999000012 mem: 3753.0...
```
And I was like, chronos man, looks like there are plenty of resources to me?
But it was a constraint issue.
This makes the error message hint at this, to benefit my future self?

Log a hint that constraints are not met for a task

---

README.md

> #mesos is for the Apache Mesos Project. It is not a support channel for frameworks/platform built on top of it.

Update README.md to point to #chronos

---

pom.xml

Updates deprecated mesosphere.io domain name to new mesosphere.com in Maven repository URL.

Update Maven repo URL downloads.mesosphere.io to .com

---

docs/docs/api.md
src/main/scala/org/apache/mesos/chronos/scheduler/api/JobManagementResource.scala
src/main/scala/org/apache/mesos/chronos/scheduler/api/PathConstants.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobSchedulerIntegrationTest.scala

Add logic in job scheduler to trigger dependencies and Pull out logic for getting new job config with incremented success into method. Add unit tests

add markJobSuccessful api call

---

docs/docs/api.md
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/UnlikeConstraint.scala
src/main/scala/org/apache/mesos/chronos/utils/JobDeserializer.scala
src/main/scala/org/apache/mesos/chronos/utils/JobSerializer.scala
src/test/scala/org/apache/mesos/chronos/scheduler/api/SerDeTest.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/constraints/UnlikeConstraintSpec.scala

Marathon supports [UnlikeConstraints](https://mesosphere.github.io/marathon/docs/constraints.html) to run tasks on slaves *not* matching a given attribute.
This adds the equivalent to Chronos. Most of this has been c+p from the LikeConstraint class, with the case conditions negated in the matches() function of the Constraint.
Warning: I don't have any prior experience writing Scala, so I'm open to ideas for cleaning this up. The range constraint has been left unimplemented as in the LikeConstraint.

add unlikeconstraint

---

src/main/scala/org/apache/mesos/chronos/scheduler/api/RedirectFilter.scala

Even with the change in https://github.com/mesos/chronos/pull/463, it still appears to be possible to end up in a state where a supposed non-leader instance ends up getting itself as the leader path. When this happens, in `RedirectFilter`, `jobScheduler.isLeader == false` but `jobScheduler.getLeader` returns the path of the current instance. This results in chronos redirecting all requests to itself, and, ultimately an unresponsive REST api. It never appears to be able to recover when in this state. If the other chronos instances think that the stuck node is the leader, they will also end up being unresponsive resulting in an unusable chronos cluster.
Unfortunately, it is a bit difficult to reproduce the problem. One way I have found where I can duplicate it with some consistency is to …

don't allow proxying requests to self

---

docs/docs/api.md
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/ConstraintChecker.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala
src/test/scala/org/apache/mesos/chronos/scheduler/mesos/ConstraintCheckerSpec.scala

per https://github.com/mesos/chronos/issues/555

auto hostname attribute

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala
src/test/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilderSpec.scala

This addresses the immediate problem mentioned in https://github.com/mesos/chronos/issues/628

Added a job's run time and attempt as environment variables exposed to the job

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

Noticed the Chronos logs tend to be overly verbose so this PR reduces the log level for the biggest offenders (at least in terms of my environment). I think this is semantically more accurate anyway--this seems like debug output to me.
Open to continuing down this path if this is useful to folks!

Drop level of biggest log spam offenders.

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala

chronos with only one server instance will be switched to `Defeated` status if it's disconnected to zookeeper and be switched to `Elected` if it's connected to zookeeper. In this case, chronos load job from zookeeper and add ScheduleStream into streams in JobScheduler. If we don't dedup ScheduleStream by jobName, the size of streams will increase unexpetedly as follows:
```
[INFO] [pool-5-thread-1] 06-10 00:01:00,468 [JobScheduler] - Size of streams: 150
......
[INFO] [pool-5-thread-1] 06-10 19:01:46,113 [JobScheduler] - Defeated. Not the current leader.
[INFO] [main-EventThread] 06-10 19:01:59,900 [ConnectionStateManager] - State change: RECONNECTED
[INFO] [pool-5-thread-1] 06-10 19:01:59,905 [JobScheduler] - Elected as leader.
....
[INFO] [pool-5-thread-1] 06-10 19:02:35,965 …
```

Dedup ScheduleStream by jobName.

---

src/main/scala/org/apache/mesos/chronos/scheduler/api/JobManagementResource.scala
src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskUtils.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobSchedulerIntegrationTest.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/TaskUtilsSpec.scala

enabling the ability to have the REST API override or add arguments to a job.

task arguments

---

docs/docs/configuration.md
src/main/scala/org/apache/mesos/chronos/scheduler/config/SchedulerConfiguration.scala

This removes the version from the default framework name. This brings Chronos inline with other frameworks that don't include the version number in this field.
I hope there's no reason why Chronos currently includes the version number, please let me know if that's the case!

Change default framework name

---

docs/docs/api.md
src/main/scala/org/apache/mesos/chronos/scheduler/api/ChronosRestModule.scala
src/main/scala/org/apache/mesos/chronos/scheduler/api/LeaderRestModule.scala
src/main/scala/org/apache/mesos/chronos/scheduler/api/PathConstants.scala

reopening after #683 was closed.
This adds a /scheduler/leader endpoint for getting the current leader.
It returns JSON in the structure of {'leader': leader}.

add an api endpoint for getting the current leader

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManagerSpec.scala

A task which was already queued should not be re-enqueued.
This is to address an issue not fully address by #750.

Don't double enqueue tasks.

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobSchedulerSpec.scala

When a job with a finite number of repetitions reaches its last
repition, it should stop (and not crash Chronos).
This fixes #772.

Properly handle `None` type.

---

docs/docs/api.md

as that section doesn't exist in the article

Remove 'Asynchronous Jobs' section from ToC

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtils.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtilsSpec.scala

This is a follow-up to #789, which missed a case where the job is
overdue and has a finite number of recurrences.

Fix for overdue jobs with finite recurrences.

---

bin/start.sh

By doing an `exec`, `java` becomes the PID 1 in the conatiner, making the chronos application receive `SIGTERM` signals sent by docker when executing a `docker stop` command.
See https://docs.docker.com/engine/reference/builder/#entrypoint for more details.

Make chronos the PID 1

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/TaskManager.scala
src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala

Job arguments which are generated just before a job is launched should
not be persisted to the state store.
This resolves #779 and #794.

Don't persist additional job arguments.

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtils.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobUtilsSpec.scala

If a job has a period which exceeds 1 month and is specified using the
month or year notation, an exception will be thrown because months and
years do not have fixed durations.

Fix for exception w/ month+ periods.

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilder.scala
src/test/scala/org/apache/mesos/chronos/scheduler/mesos/MesosTaskBuilderSpec.scala

As `MESOS_TASK_ID` is an environment variable, it should be uppercase.

Add missing MESOS_TASK_ID environment variable

---

src/main/scala/org/apache/mesos/chronos/scheduler/jobs/JobScheduler.scala
src/test/scala/org/apache/mesos/chronos/scheduler/jobs/JobSchedulerSpec.scala

If a job has 0 repititions remaining, but the schedule is in the past,
it'll cause the sleep time to be return as 0. This might fix #803.

Fix for nanosUntilNextJob() edge case.

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

Since the dawn of Mesos, executors have had the option of sending a `TASK_STARTING` update to indicate that the launch command has been received. Currently, Chronos will react to to this update by killing the task.
As far as I can tell, this should fix the issue and tests are passing, but I will admit that I have no experience with either Scala or Maven.

Don't kill executors sending a TASK_STARTING update.

---

src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala

This is the same change as in https://github.com/mesos/chronos/pull/854 , rebased onto the `stable` branch.

Don't kill executors who send a TASK_STARTING update.
